export const users = [
  {
    id: "lule",
    id2: "lule2",
    id3: "lule3",
    name: "Lule",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 0,
        tTeam: 1,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 0,
        tTeam: 1,
        lTeam: 1,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 0,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 2,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 0,
        tTeam: 0,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 2,
        tTeam: 3,
        lTeam: 0,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 1,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 0,
        sTeam: 3,
        tTeam: 2,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 0,
        sTeam: 2,
        tTeam: 1,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 0,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 1,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 0,
        tTeam: 0,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 0,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "chuchantrio",
    id2: "chuchantrio2",
    id3: "chuchantrio3",
    name: "Chuchantrio",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 2,
        tTeam: 0,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 3,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 3,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 4,
        sTeam: 1,
        tTeam: 3,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 1,
        tTeam: 2,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 2,
        tTeam: 3,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 3,
        sTeam: 1,
        tTeam: 3,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 3,
        sTeam: 0,
        tTeam: 3,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 1,
        tTeam: 3,
        lTeam: 0,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 1,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 1,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "lauri",
    id2: "lauri2",
    id3: "lauri3",
    name: "Lauri",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 1,
        tTeam: 1,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 3,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 3,
        sTeam: 2,
        tTeam: 2,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 2,
        tTeam: 1,
        lTeam: 1,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 2,
        sTeam: 2,
        tTeam: 3,
        lTeam: 0,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 2,
        sTeam: 2,
        tTeam: 2,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 1,
        tTeam: 3,
        lTeam: 3,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 1,
        sTeam: 2,
        tTeam: 2,
        lTeam: 1,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 0,
        sTeam: 3,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 3,
        sTeam: 2,
        tTeam: 3,
        lTeam: 2,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 1,
        sTeam: 1,
        tTeam: 2,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 1,
        tTeam: 3,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 2,
        sTeam: 1,
        tTeam: 3,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "nano",
    id2: "nano2",
    id3: "nano3",
    name: "Nano",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 0,
        sTeam: 0,
        tTeam: 1,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 3,
        sTeam: 0,
        tTeam: 1,
        lTeam: 2,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 3,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 3,
        tTeam: 2,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 2,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 0,
        sTeam: 3,
        tTeam: 2,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 2,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 0,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 2,
        sTeam: 1,
        tTeam: 1,
        lTeam: 1,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "jeezy",
    id2: "jeezy2",
    id3: "jeezy3",
    name: "Jeezy",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 2,
        tTeam: 1,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 3,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 4,
        sTeam: 0,
        tTeam: 1,
        lTeam: 3,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 4,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 3,
        sTeam: 1,
        tTeam: 2,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 1,
        sTeam: 3,
        tTeam: 1,
        lTeam: 1,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 2,
        sTeam: 1,
        tTeam: 4,
        lTeam: 2,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 1,
        sTeam: 0,
        tTeam: 3,
        lTeam: 0,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 0,
        sTeam: 2,
        tTeam: 1,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 1,
        tTeam: 3,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 2,
        tTeam: 3,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 3,
        sTeam: 0,
        tTeam: 3,
        lTeam: 1,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 1,
        sTeam: 0,
        tTeam: 1,
        lTeam: 2,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 0,
        sTeam: 1,
        tTeam: 2,
        lTeam: 0,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 1,
        sTeam: 2,
        tTeam: 2,
        lTeam: 2,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "shoali",
    id2: "shoali2",
    id3: "shoali3",
    name: "Shoali",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 2,
        tTeam: 0,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 2,
        sTeam: 1,
        tTeam: 2,
        lTeam: 0,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 4,
        sTeam: 0,
        tTeam: 3,
        lTeam: 1,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 0,
        tTeam: 4,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 1,
        sTeam: 2,
        tTeam: 2,
        lTeam: 1,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 2,
        sTeam: 2,
        tTeam: 1,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 2,
        sTeam: 1,
        tTeam: 4,
        lTeam: 1,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 3,
        sTeam: 1,
        tTeam: 3,
        lTeam: 0,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 2,
        sTeam: 1,
        tTeam: 1,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 1,
        sTeam: 1,
        tTeam: 3,
        lTeam: 2,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 1,
        tTeam: 3,
        lTeam: 2,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 1,
        sTeam: 2,
        tTeam: 3,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 2,
        sTeam: 1,
        tTeam: 2,
        lTeam: 2,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 0,
        tTeam: 3,
        lTeam: 2,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 1,
        sTeam: 2,
        tTeam: 2,
        lTeam: 2,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
  {
    id: "resultados",
    id2: "resultados2",
    id3: "resultados3",
    name: "Resultados reales",
    date: "Fecha 1",
    date2: "Fecha 2",
    date3: "Fecha 3",
    results: [
      {
        char: "A",
        fTeam: 0,
        sTeam: 2,
        tTeam: 0,
        lTeam: 2,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 6,
        sTeam: 2,
        tTeam: 1,
        lTeam: 1,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 1,
        sTeam: 2,
        tTeam: 0,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 0,
        sTeam: 0,
        tTeam: 4,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: 1,
        sTeam: 2,
        tTeam: 7,
        lTeam: 0,
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: 0,
        sTeam: 0,
        tTeam: 1,
        lTeam: 0,
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: 1,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: 0,
        sTeam: 0,
        tTeam: 3,
        lTeam: 2,
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results2: [
      {
        char: "A",
        fTeam: 1,
        sTeam: 3,
        tTeam: 1,
        lTeam: 1,
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: 0,
        sTeam: 2,
        tTeam: 0,
        lTeam: 0,
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: 2,
        sTeam: 0,
        tTeam: 2,
        lTeam: 0,
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: 0,
        sTeam: 1,
        tTeam: 2,
        lTeam: 1,
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    results3: [
      {
        char: "A",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "",
        sTeam: "",
        tTeam: "",
        lTeam: "",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Ecuador",
        tTeam: "Senegal",
        lTeam: "Holanda",
        fFlag: "qatar.png",
        sFlag: "ecuador.png",
        tFlag: "senegal.png",
        lFlag: "netherlands.png",
      },
      {
        char: "B",
        fTeam: "Inglaterra",
        sTeam: "Irán",
        tTeam: "EEUU",
        lTeam: "Gales",
        fFlag: "england.png",
        sFlag: "iran.png",
        tFlag: "united-states.png",
        lFlag: "wales.png",
      },
      {
        char: "C",
        fTeam: "Argentina",
        sTeam: "Arabia Saudí",
        tTeam: "México",
        lTeam: "Polonia",
        fFlag: "argentina.png",
        sFlag: "saudi-arabia.png",
        tFlag: "mexico.png",
        lFlag: "poland.png",
      },
      {
        char: "D",
        fTeam: "Dinamarca",
        sTeam: "Túnez",
        tTeam: "Francia",
        lTeam: "Australia",
        fFlag: "denmark.png",
        sFlag: "tunisia.png",
        tFlag: "france.png",
        lFlag: "australia.png",
      },
      {
        char: "E",
        fTeam: "Alemania",
        sTeam: "Japón",
        tTeam: "Espana",
        lTeam: "Costa Rica",
        fFlag: "germany.png",
        sFlag: "japan.png",
        tFlag: "spain.png",
        lFlag: "costa-rica.png",
      },
      {
        char: "F",
        fTeam: "Marruecos",
        sTeam: "Croacia",
        tTeam: "Bélgica",
        lTeam: "Canadá",
        fFlag: "morocco.png",
        sFlag: "croatia.png",
        tFlag: "belgium.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Suiza",
        sTeam: "Camerún",
        tTeam: "Brasil",
        lTeam: "Serbia",
        fFlag: "switzerland.png",
        sFlag: "cameroon.png",
        tFlag: "brazil.png",
        lFlag: "serbia.png",
      },
      {
        char: "H",
        fTeam: "Uruguay",
        sTeam: "Corea del Sur",
        tTeam: "Portugal",
        lTeam: "Ghana",
        fFlag: "uruguay.png",
        sFlag: "south-korea.png",
        tFlag: "portugal.png",
        lFlag: "ghana.png",
      },
    ],
    groupsData2: [
      {
        char: "A",
        fTeam: "Qatar",
        sTeam: "Senegal",
        tTeam: "Holanda",
        lTeam: "Ecuador",
        fFlag: "qatar.png",
        sFlag: "senegal.png",
        tFlag: "netherlands.png",
        lFlag: "ecuador.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Irán",
        tTeam: "Inglaterra",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "iran.png",
        tFlag: "england.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Arabia Saudí",
        tTeam: "Argentina",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "saudi-arabia.png",
        tFlag: "argentina.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Australia",
        tTeam: "Francia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "australia.png",
        tFlag: "france.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Costa Rica",
        tTeam: "Espana",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "costa-rica.png",
        tFlag: "spain.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Bélgica",
        sTeam: "Marruecos",
        tTeam: "Croacia",
        lTeam: "Canadá",
        fFlag: "belgium.png",
        sFlag: "morocco.png",
        tFlag: "croatia.png",
        lFlag: "canada.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Serbia",
        tTeam: "Brasil",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "serbia.png",
        tFlag: "brazil.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Ghana",
        tTeam: "Portugal",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "ghana.png",
        tFlag: "portugal.png",
        lFlag: "uruguay.png",
      },
    ],
    groupsData3: [
      {
        char: "A",
        fTeam: "Holanda",
        sTeam: "Qatar",
        tTeam: "Ecuador",
        lTeam: "Senegal",
        fFlag: "netherlands.png",
        sFlag: "qatar.png",
        tFlag: "ecuador.png",
        lFlag: "senegal.png",
      },
      {
        char: "B",
        fTeam: "Gales",
        sTeam: "Inglaterra",
        tTeam: "Irán",
        lTeam: "EEUU",
        fFlag: "wales.png",
        sFlag: "england.png",
        tFlag: "iran.png",
        lFlag: "united-states.png",
      },
      {
        char: "C",
        fTeam: "Polonia",
        sTeam: "Argentina",
        tTeam: "Arabia Saudí",
        lTeam: "México",
        fFlag: "poland.png",
        sFlag: "argentina.png",
        tFlag: "saudi-arabia.png",
        lFlag: "mexico.png",
      },
      {
        char: "D",
        fTeam: "Túnez",
        sTeam: "Francia",
        tTeam: "Australia",
        lTeam: "Dinamarca",
        fFlag: "tunisia.png",
        sFlag: "france.png",
        tFlag: "australia.png",
        lFlag: "denmark.png",
      },
      {
        char: "E",
        fTeam: "Japón",
        sTeam: "Espana",
        tTeam: "Costa Rica",
        lTeam: "Alemania",
        fFlag: "japan.png",
        sFlag: "spain.png",
        tFlag: "costa-rica.png",
        lFlag: "germany.png",
      },
      {
        char: "F",
        fTeam: "Croacia",
        sTeam: "Bélgica",
        tTeam: "Canadá",
        lTeam: "Marruecos",
        fFlag: "croatia.png",
        sFlag: "belgium.png",
        tFlag: "canada.png",
        lFlag: "morocco.png",
      },
      {
        char: "G",
        fTeam: "Camerún",
        sTeam: "Brasil",
        tTeam: "Serbia",
        lTeam: "Suiza",
        fFlag: "cameroon.png",
        sFlag: "brazil.png",
        tFlag: "serbia.png",
        lFlag: "switzerland.png",
      },
      {
        char: "H",
        fTeam: "Corea del Sur",
        sTeam: "Portugal",
        tTeam: "Ghana",
        lTeam: "Uruguay",
        fFlag: "south-korea.png",
        sFlag: "portugal.png",
        tFlag: "ghana.png",
        lFlag: "uruguay.png",
      },
    ],
  },
];

export const groupsData = [
  {
    char: "A",
    fTeam: "Qatar",
    sTeam: "Ecuador",
    tTeam: "Senegal",
    lTeam: "Holanda",
    fFlag: "qatar.png",
    sFlag: "ecuador.png",
    tFlag: "senegal.png",
    lFlag: "netherlands.png",
  },
  {
    char: "B",
    fTeam: "Inglaterra",
    sTeam: "Irán",
    tTeam: "EEUU",
    lTeam: "Gales",
    fFlag: "england.png",
    sFlag: "iran.png",
    tFlag: "united-states.png",
    lFlag: "wales.png",
  },
  {
    char: "C",
    fTeam: "Argentina",
    sTeam: "Arabia Saudí",
    tTeam: "México",
    lTeam: "Polonia",
    fFlag: "argentina.png",
    sFlag: "saudi-arabia.png",
    tFlag: "mexico.png",
    lFlag: "poland.png",
  },
  {
    char: "D",
    fTeam: "Dinamarca",
    sTeam: "Túnez",
    tTeam: "Francia",
    lTeam: "Australia",
    fFlag: "denmark.png",
    sFlag: "tunisia.png",
    tFlag: "france.png",
    lFlag: "australia.png",
  },
  {
    char: "E",
    fTeam: "Alemania",
    sTeam: "Japón",
    tTeam: "Espana",
    lTeam: "Costa Rica",
    fFlag: "germany.png",
    sFlag: "japan.png",
    tFlag: "spain.png",
    lFlag: "costa-rica.png",
  },
  {
    char: "F",
    fTeam: "Marruecos",
    sTeam: "Croacia",
    tTeam: "Bélgica",
    lTeam: "Canadá",
    fFlag: "morocco.png",
    sFlag: "croatia.png",
    tFlag: "belgium.png",
    lFlag: "canada.png",
  },
  {
    char: "G",
    fTeam: "Suiza",
    sTeam: "Camerún",
    tTeam: "Brasil",
    lTeam: "Serbia",
    fFlag: "switzerland.png",
    sFlag: "cameroon.png",
    tFlag: "brazil.png",
    lFlag: "serbia.png",
  },
  {
    char: "H",
    fTeam: "Uruguay",
    sTeam: "Corea del Sur",
    tTeam: "Portugal",
    lTeam: "Ghana",
    fFlag: "uruguay.png",
    sFlag: "south-korea.png",
    tFlag: "portugal.png",
    lFlag: "ghana.png",
  },
];
